### ISSUE TITLE
Occasionally will generate `stem` elements with ` == \n` after

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/reverse_asciidoctor#10]
For example, this equation in Word `(i - 8j + 1) -th` becomes:

```
stem:[(i - 8j + 1)] == 
th
```

**Comment by opoudjis** [comment]
I cannot replicate this; see the attached. Please send the document causing this behaviour.

**Comment by opoudjis** [comment]
[ith.zip](https://github.com/riboseinc/reverse_asciidoctor/files/1962493/ith.zip)

**Comment by ronaldtse** [comment]
The `part5.adoc` file you sent me before had this issue.

**Comment by opoudjis** [comment]
part1.adoc. Regenerating document to see if it's since gone away.

**Comment by opoudjis** [comment]
No, it's still there.

**Comment by ronaldtse** [comment]
I'm glad it's reproduced now 😉

**Comment by opoudjis** [comment]
Worse: the second `== the` is actually the superscript -th, *encoded as `<h1>`*!!!!

`<h1 class="T3" style="vertical-align: super; font-size: 58%; margin: 0;">th</h1>`

Nuts. Just nuts. I am massaging the HTML to detect such headers and replace them with `<sup>`

**Comment by opoudjis** [comment]
This means that the LibreOffice Word converter is problematic. I am still not going to abandon it, because rewriting it would be a sizeable project.

**Comment by opoudjis** [comment]
Am also debugging the removal of spaces after stem expressions

**Comment by opoudjis** [comment]
There are going to be many other malfeatures of the LibreOffice conversion; but this can't be a high priority...

**Comment by ronaldtse** [comment]
I agree, let’s just hang on to Libreoffice and accept this for now.
