### ISSUE TITLE
Moving `w2a` to a separate gem

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/reverse_asciidoctor#8]
Given that https://github.com/benbalter/word-to-markdown is a separate gem shouldn't `w2a` be in a separate repo?

**Comment by opoudjis** [comment]
Disagree. W2a is a utility script, not a separate gem.

**Comment by ronaldtse** [comment]
Is it not a counterpart to https://github.com/benbalter/word-to-markdown ?

**Comment by opoudjis** [comment]
Yes. I still don't see why it needs to be in a separate gem. The script does not add much functionality to word-to-markdown, and all the functionality that matters is in this gem.

**Comment by opoudjis** [comment]
Leaving in the gem

**Comment by opoudjis** [comment]
I already do

**Comment by ronaldtse** [comment]
Oh right. It's just a bit hidden...

**Comment by opoudjis** [comment]
To do: rearrange Readme
