### ISSUE TITLE
Conflicting executable with "w2m"

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/reverse_asciidoctor#9]
Running gem install gives this warning:

```
reverse_asciidoctor's executable "w2m" conflicts with word-to-markdown
Overwrite the executable? [yN]  
```

The executable should be called "w2a" instead.

**Comment by opoudjis** [comment]
... It already is; please update gem

**Comment by ronaldtse** [comment]
Yes, I've had to re-release gem https://github.com/riboseinc/reverse_asciidoctor/commit/30ec9a1f1aee1b9b174f666e1c41a85d0117a55d
